### ISSUE TITLE
Modified invite request pictures to re-use, also make invite photos non-VRC+.

### ISSUE THREAD

**Issue by Meeran1675** [DubyaDude/RubyClientPublic#142]
This might be interpreted differently, but I'm intending to pitch a feature to modify invite notification pictures. Whether it's saving ones you took already to be able to re-use them, or to grab a .png off of your desktop and forward memes and basically any .png that you want. Please also try to make it accessible to non VRChat Plus users.

**Comment by DubyaDude** [comment]
Firstly, 2 suggestions in one so I can't consider this a valid suggestion.

Second, I'm not planning on adding circumvention to any VRC+ feature. I've let the favorite list stay because it's been in RubyClient for **years**. Basically, if there are any new features that get added to VRC+ that isn't already in RubyClient, expect me to never implement them. That's just an easy way to get your ass sued.

Please learn to support the developers of the game that you've probably spent a lot of time in just as I have.
