### ISSUE TITLE
Member count channel thingy

### ISSUE THREAD

**Issue by KeafyIsHere** [DubyaDude/RubyClientPublic#34]
live ruby member count as a voice channel on the discord.

yuh

**Comment by DubyaDude** [comment]
I've thought about doing so for quite some time, however there's a few issues with it.

Firstly, accuracy and API limits. While the host is great at keeping DDOS attacks out, it's not the best in terms of 100% stable connections. There are often temporary disconnects, usually caused by users. With RubyBot now fully public and constant player count changes, I have to look into more API limitation issues. Adding that feature would add more API calls to discord end of things (I believe), so at the moment, I'd rather not go through all that.

Second, Statistical Anonymity. Don't think that's the correct term but that's how I'll use it. With math and enough data you could reverse certain statistics to get an accurate mapping on who said what on certain stats (a nice video shown [here](https://www.youtube.com/watch?v=pT19VwBAqKA)). While just releasing a ruby player count probably wouldn't give nearly enough data, I'd rather be safe then sorry and uphold rubys in-game privacy as much as possible.
