### ISSUE TITLE
Suggestion: Add an indicator that a user hid your avatar.

### ISSUE THREAD

**Issue by fwenny** [DubyaDude/RubyClientPublic#48]
Something similar to how it handles block / being blocked perhaps?

**Comment by Murkur** [comment]
this already exists in the Moderation module as a heads up displayy option aswell as appearing in the ruby console by default

**Comment by fwenny** [comment]
doesnt help me if they hid me before I / they joined.

**Comment by Murkur** [comment]
fair point if this was added it could be placed on the nameplate

**Comment by DubyaDude** [comment]
This would now include bringing back Avatar Hide/Unhide Notifs. I've stated that this involves doing extra API requests but never explained how horribly it would need to be implemented.

There are 3 types of Moderation the game handles, globalModerations, ModerationsAgainstMe, ModerationsAgainstOthers 
globalModerations includes bans and kicks
ModerationsAgainstMe includes people who have you blocked/muted/hidden/unhidden
ModerationsAgainstOthers includes people you have blocked/muted/hidden/unhidden

**BEFORE**
All 3 of these used to be stored in-game through the WebAPI. Meaning VRChat did these API requests themselves (this will be important later on).
But, that's not how we got the notification for hide/unhide. We do this through something called RPC, which is basically a way to send data between players. When someone hides/unhides another player, an RPC is sent alerting every player in the lobby of the action, horribly network design, but something we took advantage of.

**AFTER**
After Moderation got rewritten, everything changed. First of all, only 2 Moderations are handled from the WebAPI now, globalModerations and ModerationsAgainstOthers. And now when a player hides/unhides, no notification gets sent out to anyone that an action occurred.
So, that means in order to implement hide/unhide notifs, we'd need to do a WebAPI request for ModerationsAgainstMe (can't be proxied) and request it fast enough so that it's somewhere close to real-time, but not too fast to raise suspicions, which if you can't tell is nearly impossible.

Because of this, I don't feel uncomfortable implementing it back because they're more than welcome to shut down that endpoint and nothing in terms of vanilla VRC would break, from my experience they eventually will.
