### ISSUE TITLE
Suggestion: Dynamic bone friends only in base module

### ISSUE THREAD

**Issue by kalyxVRC** [DubyaDude/RubyClientPublic#66]
Is it possible to split the "Limit dynamic bones to friends only" from Touch and include it in Base? I'm wondering if y'all can make that available before you start working on releasing touch again.

**Comment by jerk** [comment]
I'm confused on what you are trying to say. Can you elaborate a bit better?

**Comment by kalyxVRC** [comment]
Mainly asking if the setting from touch called "dynamic bones for friends only" can be bumped up in priority. But also in general, maybe moving that feature from touch to the base module. It's the only thing i ever used touch for. Very nice for performance in game.

**Comment by DubyaDude** [comment]
Touch is going through a full re-work. There is no longer a "dynamic bones for friends only" button, but rather a profile for ranks/individual users (frostbyte can elaborate more when we're ready to release since that's been his project).

That being said, both me and Frostbyte are going through final exams, and we can't really split it and push out a 'lite' version to base.
