### ISSUE TITLE
(Suggestion) Anti avatar save

### ISSUE THREAD

**Issue by eidod23** [DubyaDude/RubyClientPublic#74]
In recent update a person can steal a avatars from their library folder. if ruby could safe guard my avatars i would be greatful heres a tutorial of how to steal avatars through vrchat https://youtu.be/EOBcfJLEIh0 i real hope this can be blocked.

**Comment by DaytonaX2** [comment]
I would like to let you know that that is called ripping avatars, its been around for a while now and multiple ways to do it.

**Comment by DubyaDude** [comment]
As @DaytonaX2 said, this is referred to as ripping. Unfortunately, there will never be a true way to 'block' ripping, because if a player has to LOAD an asset (such as Avatars), there's a way to rip it. 
There ARE ways to make it difficult, however, this comes down to the model structure/upload itself (like custom VRChat SDKs or a scrambler in Blender).
This cannot be done via Client/Game Mod

**Comment by OptoCloud** [comment]
I think it was sketchfab that had a really good obfuscator/scrambler, but still is prone to ripping.
Alot of the more realistic models in vrc are most likely ripped from some other games like:
Final Fantasy
Skyrim
Dark Souls
Half Life Alyx
etc etc...
Ripping will always be a thing and is unavoidable unless you stream the gameplay as videoframes over the internet,
and have the actual game itself running server-side.
(but that has latency issues and alot of other problems)
