### ISSUE TITLE
[Feature Request] Anti World Desync

### ISSUE THREAD

**Issue by Nin2648** [DubyaDude/RubyClientPublic#77]
There are a lot of client users as of recent that have been abusing world desync and lag / break the entire lobby. This also seems to be paired with world objects repeatedly colliding into each other, which takes a lot of processing power and results in lag. It would be great if it were possible to have an anti for that :D

**Comment by RubyYuukoShionji** [comment]
Can you please elaborate specifially what you mean / put into the term world desync.

**Comment by Nin2648** [comment]
I am not sure how exactly it works, but there is currently an exploit going around that allows some client users to abuse world object collisions in order to lag everybody. Whichever method it may be, the module just causes an immense lag to every user in the lobby and just 'kills' the lobby. I say desync because all conversation and movement lags severely or is just halted as a result of it. It's becoming increasingly more common and ruins the vrc experience.

**Comment by CryCry34** [comment]
This is caused by objects colliding with each other repeatedly, 
causing too many requests being sent back and forth between players and the server 
causing the "lagg" and or "halt". 
A way to solve this would be to add a toggle for object to object collision, 
and or disable collision/simulation of objects all together.
This is something which was changed in recent updates causing this random object spass.
(You don't have to use a client to reproduce this, it is done by just stacking props ontop of each other and or in a pile in a very close proximity)

**Comment by jerk** [comment]
Currently, people abuse VRChat's networking. The way people are currently doing is by sending an event with an invalid payload which interrupts game logic and event dequeuing until the next frame. Yes, this is still an issues.

**Comment by DubyaDude** [comment]
Donezo (new sub-module in base called RubySelfProtection)
