### ISSUE TITLE
Blocking Avatars by USR ID

### ISSUE THREAD

**Issue by Myrkie** [DubyaDude/RubyClientPublic#81]
Blocking avatars via usr-id for common public crashes or users that are known for creation of undesirable avatars

Suggested Tags (item:avatar)

**Comment by RubyYuukoShionji** [comment]
Isnt this what the "hide avatar" button is for?

**Comment by Murkur** [comment]
> Isnt this what the "hide avatar" button is for?

Kind of annoying to find people that raid with multiple of the same obnoxious avatar as well as the Quick menu breaking when theirs low Framerate making it impossible to select users

**Comment by Murkur** [comment]
so instead of blocking a usrs avatar it blocks that avatar for anyone who uses it aswell as all avatars created by that usr so example blocking an avatar by a known crasher (usr_a55d0255-cd82-4e16-a3ea-7760c0d8d363) will block all avatars he has created inless you manually show avatar for a person that happens to be using one of their public avatars, some other clients had this as a one time use against NAS were it would block all avatars by NAS and only NAS

**Comment by RubyYuukoShionji** [comment]
So in other words block all avatars uploaded by someone who is "black listed" ?

**Comment by Murkur** [comment]
> So in other words block all avatars uploaded by someone who is "black listed" ?

exactly just select a user or add a user ID to a config file and it blocks all avatars they have uploaded to their account regardless of who is wearing them
