### ISSUE TITLE
[Feature Request] Add teleport to mirror button to make MirrorSimulator™ even better

### ISSUE THREAD

**Issue by OptoCloud** [DubyaDude/RubyClientPublic#92]
Teleport to nearest mirror and activate it by the click of a button
This is a very important feature that needs to be added :)

**Comment by RubyYuukoShionji** [comment]
I see this is a super serious suggestion, so I'll give a super serious answer.

Great idea but unfortunetly due to those big mean world authors that care about framerates and dare optimize their map, this is not viable.

</Sarcasm>

Because of the way many world are optimized(disabling game objects in areas the player is not in) teleporting there would not often trigger the zone triggers loading in the area. Thus everything would still be gone.
