### ISSUE TITLE
Add legacy locomotion enable for UDON worlds

### ISSUE THREAD

**Issue by Janni9009** [DubyaDude/RubyClientPublic#97]
Two suggestions for today, this being the second. This will enable legacy movement in UDON worlds (gliding, wallclimbing) and requires no obfuscated fields as far as i can tell with ML.
using directive is VRC.SDKBase, the single liner needed then is "Networking.LocalPlayer.UseLegacyLocomotion();"
this is a one way toggle though, so once its on you need to rejoin to turn it back off

**Comment by DubyaDude** [comment]
Ruby is about to have it's own 'Jump Controller'
With that, I'm adding an 'Infinite Jump' mode where every time you click jump, you jump, on the ground or not. It doesn't act exactly like the Legacy one though.

With that being soon a thing, I'm not sure if this is needed.
If you feel otherwise go ahead and let me know.

**Comment by Murkur** [comment]
> Ruby is about to have it's own 'Jump Controller'
> With that, I'm adding an 'Infinite Jump' mode where every time you click jump, you jump, on the ground or not. It doesn't act exactly like the Legacy one though.
> 
> With that being soon a thing, I'm not sure if this is needed.
> If you feel otherwise go ahead and let me know.

Oh ive been waiting for something like this for awhile since ive seen it possible in other clients

**Comment by DubyaDude** [comment]
> Oh ive been waiting for something like this for awhile since ive seen it possible in other clients
Mhm, seems like my burnout is finally over, so going module by module and implementing some of these
